include:
  - media-compose.yml
  - immich/docker-compose.yml
  - paperless-ngx/docker-compose.yml

networks:
  app:
    driver: bridge

services:
  caddy:
    build: ./caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - app
  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - TZ=${TZ?err}
      - HOMEPAGE_ALLOWED_HOSTS=lab.baddog.ch,ubuntu.bonobo-torino.ts.net:3000
    networks:
      - app

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    networks:
      - app

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - DISPLAY_TIMEZONE=${TZ?err}
      - APP_KEY=base64:TJcMxaFHNF3SQDcGeFsk6NF5GOCAGX71TU+2RyYmzFM=
      - SPEEDTEST_SCHEDULE=15 */6 * * *  # Every 6th hour, on th 15-th minute
    volumes:
      - ./speedtest-tracker:/config
    networks:
      - app
  
  actual:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
      #environment:
      #- ACTUAL_LOGIN_METHOD=header
    networks:
      - app
    volumes:
      - ./actual:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime-kuma:/app/data
    networks:
      - app

volumes:
  caddy-data:
  caddy-config:
