---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: baddog Homepage
theme: dark # <----- add this line
color: stone # <----- add this line
background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80 # <----- add this line
  # blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 80 # 0-100


providers:
  openweathermap: 4ee8ec1b02b963463851bd1ba58ef05a
    # weatherapi: weatherapiapikey
